# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  
  lane :run_test do
    scan(scheme: "CodeCoverageExample",
         code_coverage: true,
        clean: true,
        derived_data_path: "../testOutput/",
        skip_build: true
        )
  end

  lane :slather_run do
    slather(build_directory: "../testOutput/",
      scheme: "CodeCoverageExample",
      proj: "CodeCoverageExample.xcodeproj",
      output_directory: "../testOutput/slatherOutput", 
      cobertura_xml: true,
      ignore: ["Pods/*", "ThirdParty/*", “Frameworks/*"]
   )
  end
end
